#!/usr/bin/env bash

[ -z ${DOCKER_REPO-} ] && exit 1
[ -z ${NAME-} ] && exit 1

VERSION=$(if [ -z ${VERSION-} ]; then echo $(if [ -z ${DOCKER_TAG-} ]; then echo latest; else echo $DOCKER_TAG; fi); else echo $VERSION; fi)

IMAGE_NAME=$(if [ -z ${IMAGE_NAME-} ]; then echo $DOCKER_REPO/$NAME:$VERSION; else echo $IMAGE_NAME; fi)

pushd $(cd -P -- "$(dirname -- "$0")" && pwd -P)/..

./scripts/build

IMAGE_NAME=${IMAGE_NAME} docker-compose -f docker-compose.test.yml up --detach

docker logs -f docker_sut_1

RET=`docker wait docker_sut_1`

popd

exit $RET
